name: Checklist Submission
description: Submit a new checklist for a tool
title: "Checklist: "
labels: ["checklist"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for choosing to submit a new checklist! 
        
        Please take a quick look at the [submission workflow](https://github.com/nmind/proceedings?tab=readme-ov-file#workflow).
  
  - type: textarea
    id: checklist
    attributes:
      label: Checklist content
      description: Provide the JSON checklist content
      placeholder: 'ex. {"name": "tool name"}'
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Additional information
      description: Please provide us with any additional information
    validations:
      required: false

  - type: checkboxes
    id: agreement
    attributes:
      label: Agreement
      description: By submitting this checklist, you understand and agree to the submission process.
      options:
        - label: I agree
          required: true